name: Build Windows
on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: windows-2022

    defaults:
      run:
        shell: pwsh
        working-directory: openspot-desktop

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Write env file
        run: |
          Set-Content -Path .env -Value "DAB=${{ secrets.DAB }}" -Encoding UTF8

      - name: Install deps
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Pack
        run: npm run electron-pack

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openspot-windows-build
          path: openspot-desktop/dist/**
          if-no-files-found: warn