name: Build windows
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup node js
              uses: actions/setup-node@v5
              with:
                node-version: '20'
            - name: Pack dependencies, build and pack
              working-directory: ./openspot-music-electron
              run: |
                ls
                npm install
                npm run build
                npm run electron-pack
            - name: Collecting artifacts
              uses: actions/upload-artifact@v4
              with:
                name: electron-app-build
                path: ./openspot-music-electron